### ISSUE TITLE
kubectl with gscloud creates "cache" directory in current working directory

### ISSUE THREAD

**Issue by dennisjac** [gridscale/gscloud#11]
After executing `kubectl` in several directories I noticed that a sub-directory "cache" is created every time. If gscloud wants to cache data it should probably create that folder in `~/.config/gridscale` instead.

**Comment by itakouna** [comment]
@dennisjac we already solve this issue in this https://github.com/gridscale/gscloud/pull/9. We will release a new binary ASAP.

**Comment by itakouna** [comment]
solved this issue in this #9
