### ISSUE TITLE
Update k8s dependencies

### ISSUE THREAD

**Issue by bkircher** [gridscale/gscloud#117]
This code is a bit unmaintained. Make sure to not loose contact to upstream and update 

	- k8s.io/apimachinery v0.0.0-20190925235427-62598f38f24e
	- k8s.io/client-go v0.0.0-20190802021151-fdb3fbe99e1d

dependencies. API changed though.

See 
- https://pkg.go.dev/k8s.io/apimachinery
- https://pkg.go.dev/k8s.io/client-go

**Comment by nvthongswansea** [comment]
Close because PR #119 has been merged
