### ISSUE TITLE
Add `gscloud postgres releases`

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/gscloud#122]
Similar to #113. Since we are adding [postgres resource](https://github.com/gridscale/terraform-provider-gridscale/pull/145) to gridscale tf provider, it is convenient for the user to use gscloud to get the releases of postgresSQL service in gridscale. 
Example output:
```
$ gscloud postgres releases 
10
11
12
13   
```

**Comment by bkircher** [comment]
Hmm, let's make this  `gscloud postgresql releases`. Think that the "official" name might be better everywhere, right?

**Comment by fkr** [comment]
Basically the various sql databases are - from a product view - flavours of the "gridsql". Since we use that terminology everywhere, it might make sense to have it under 'gridsql' in gscloud as well.

**Comment by bkircher** [comment]
Good point. Still, the commands would then look like

```
$ gscloud gridsql postgresql releases
$ gscloud gridsql mariadb releases
```
vs.
```
$ gscloud postgresql releases
$ gscloud mariadb releases
```
As well as the already existing
```
$ gscloud kubernetes releases
```

Personally I would go with the second option because of typing  ergonomics :wink: . What do you guys prefer?

**Comment by MarcHarriss** [comment]
Second one imo :)

**Comment by itakouna** [comment]
I would also prefer gscloud `<product_name>` `< flavour>`. This keeps `gscloud` consistent with the API and Panels.

**Comment by bkircher** [comment]
Second one +1 here, too…. so would go with that
