### ISSUE TITLE
"gscloud kubernetes cluster" prints wrong usage

### ISSUE THREAD

**Issue by g0dsCookie** [gridscale/gscloud#137]
Hi,

the help page for `gscloud kubernetes cluster` prints "gscloud postgresql cluster" as usage instead of "gscloud kubernetes cluster".

The error itself comes this Line: https://github.com/gridscale/gscloud/blob/master/cmd/postgresql.go#L75

Removing this line fixes the wrong output. I couldn't find any other reference to `clusterCmd` within postgresql context, so it should be save to remove the line.

**Comment by nvthongswansea** [comment]
@g0dsCookie Thank you for reporting this issue.
