### ISSUE TITLE
Add ssh key management to gscloud

### ISSUE THREAD

**Issue by bkircher** [gridscale/gscloud#30]
I was thinking about something like
```
$ gscloud ssh-key ls
```

```
$ gscloud ssh-key add --name test@eample.com --file ~/.ssh/id_rsa.pub
```

or even from stdin with

```
$ cat ~/.ssh/id_rsa.pub | gscloud ssh-key add
```

**Comment by itakouna** [comment]
@bkircher I would prefer 
`$ gscloud ssh-key add --name test@eample.com --file ~/.ssh/id_rsa.pub`
to keep consistent cmd line format.

**Comment by bkircher** [comment]
Lets start with that then :slightly_smiling_face:

**Comment by c0dehard** [comment]
Everything works, just the add command causes Code: 400 can someone take an eye on it please? 😄
