### ISSUE TITLE
Support --quiet flag

### ISSUE THREAD

**Issue by bkircher** [gridscale/gscloud#33]
Add a `--quiet` flag to server, network, and other resources sub-commands. If given it should only print the UUID of the resource. For example:

```
$ gscloud server ls --quiet
8bbc3917-a0c0-42c5-b3b7-2087cc33cb82
1eebb354-7cc7-4b4b-8e7a-65ffeccc7359
```

It only prints the UUID to stdout followed by a newline. No table header is printed.

This would enable us to write things like

```
$ gscloud server ls --quiet | while read s; do
    gscloud server off -f $s
done
```

**Comment by c0dehard** [comment]
Shall `--quiet` apply for all commands so they can print `ID` only as well?

**Comment by bkircher** [comment]
Sure
