### ISSUE TITLE
gscloud path lookup might fail when executed from search path

### ISSUE THREAD

**Issue by twiebe** [gridscale/gscloud#5]
When gscloud is located in $PATH and executed in credential plugin mode with neither absolute nor relative path, but rather through search path lookup, path to gscloud is not correctly determined and stored in kubeconfig.

F.e. with gscloud located in /home/user/bin, /home/user/bin being in $PATH of user `user` and gscloud being executed with `$ gscloud kubernetes cluster ...` in current working dir `/home/user`, the resulting `command` inside kubeconfig will be `/home/user/gscloud` instead of `/home/user/bin/gscloud`

**Comment by itakouna** [comment]
@twiebe can I close this issue?

**Comment by itakouna** [comment]
solved by #6
