### ISSUE TITLE
feature request: "kubectl exec" similar access to tty of vm

### ISSUE THREAD

**Issue by toastbrotch** [gridscale/gscloud#99]
i would love to get access to my linux-vms without going thru the webinterface.

(btw: where can i post feature request for the web-ui? with none of my mobile-browsers i'm able to use the console)

thanx and cheers.ivo

**Comment by bkircher** [comment]
Howdy :wave:  You mean SSH?

**Comment by toastbrotch** [comment]
no, i mean the same Terminal as in the webinterface

**Comment by bkircher** [comment]
Ah, that would be the VNC console.

I think you can already do that by using whatever VNC client you have available. Erm, let me get back to you later

**Comment by toastbrotch** [comment]
hm. if that target vm is not on public networks this wont work with vnc. besides vm needs to have installed some vnc. but as the webfrontend has already access to the TTY (i'm talking about linux-vms), i wish to have access to that via cli.

**Comment by bkircher** [comment]
Well, there is not _really_ a tty but if you do something like (off the top of my head)

```
gscloud server ls --json | jq
```
You might get something like this returned 
```json
[                  
  {                 
    "server": {         
      "object_uuid": "xyz",
      "name": "My server",
      "memory": 1,             
      "console_token": "very very long string"
    }
  }
]
```

You can use the console token to connect to your server, disregard of whether they are on the pub net or not.

The URL would look like 
```
wss://api.gridscale.io/console/?token=that very very long string from above
```

**Comment by toastbrotch** [comment]
ok. i wish i had a direct way with gscloud to get that console (without getting tokens nor talking wss) ;-)

**Comment by bkircher** [comment]
Yep. Well implementing a VNC console for gscloud is a bit out of scope, I think.

> where can i post feature request for the web-ui?

Ah, missed that. You can always reach out via support@gridscale.io. They're happy to forward feedback. You can find a link in the profile menu in the Web UI.

**Comment by bkircher** [comment]
Closing this. Feel free to re-open if there is anything left to be done

**Comment by toastbrotch** [comment]
just in case someone searches how to do connect to the console of your vm:
set up gscloud and then:
gscloud server ls --json | jq

and then connect for example with https://novnc.com/noVNC/vnc.html with these settings:

encryption: yes
server: api.yourcloudprovider_as_in_gscloud.com
port: 443
path: console/?token=<console_token_from_above>
